import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Triggers a bulletproof browser file download for the generated jsPDF document.
 */
function triggerDownload(doc, filename) {
  try {
    const blob = doc.output('blob');
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.style.display = 'none';
    document.body.appendChild(link);
    link.click();
    setTimeout(() => {
      if (document.body.contains(link)) {
        document.body.removeChild(link);
      }
      URL.revokeObjectURL(url);
    }, 500);
  } catch (err) {
    console.warn('Blob download failed, using doc.save fallback:', err);
    doc.save(filename);
  }
}

/**
 * Generates and downloads a comprehensive LabelSure Legal Metrology Compliance PDF Report.
 * 
 * @param {Object} options
 * @param {Array} options.scans - List of scan records to include
 * @param {string} [options.verdictFilter] - Current active verdict filter
 * @param {string} [options.searchQuery] - Current search query
 * @param {Object} [options.user] - Logged in officer/admin user
 * @param {number} [options.totalCount] - Total scan count
 */
export function exportCompliancePdf({
  scans = [],
  verdictFilter = '',
  searchQuery = '',
  user = null,
  totalCount = null,
}) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 36;

  // Colors
  const brandBlue = [21, 101, 192];     // #1565C0
  const brandTeal = [0, 137, 123];      // #00897B
  const safeGreen = [46, 125, 50];      // #2E7D32
  const alertRed = [198, 40, 40];       // #C62828
  const alertAmber = [217, 119, 6];     // #D97706
  const textDark = [30, 41, 59];
  const textMuted = [100, 116, 139];

  // 1. Header Banner
  doc.setFillColor(...brandBlue);
  doc.rect(0, 0, pageWidth, 72, 'F');

  // Accent Teal Stripe
  doc.setFillColor(...brandTeal);
  doc.rect(0, 72, pageWidth, 4, 'F');

  // Title & Subtitle
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('LabelSure', margin, 32);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(224, 242, 254);
  doc.text('Legal Metrology Compliance & Inspection Report', margin, 48);
  doc.text('Automated Label Verification System', margin, 60);

  // Right Header Info
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
  const timeStr = now.toLocaleTimeString('en-IN', {
    hour: '2-digit',
    minute: '2-digit',
  });

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(`Report Date: ${dateStr} ${timeStr}`, pageWidth - margin, 32, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated By: ${user?.name || user?.email || 'Authorized Officer'}`, pageWidth - margin, 46, { align: 'right' });
  doc.text(`Role: ${(user?.role || 'OFFICER').toUpperCase()}`, pageWidth - margin, 60, { align: 'right' });

  // 2. Executive Summary Metrics
  const total = totalCount || scans.length;
  const compliant = scans.filter(s => s.verdict === 'COMPLIANT').length;
  const nonCompliant = scans.filter(s => s.verdict === 'NON_COMPLIANT').length;
  const review = scans.filter(s => s.verdict === 'NEEDS_REVIEW' || s.needs_manual_review).length;
  const compRate = total > 0 ? Math.round((compliant / total) * 100) : 0;

  let yPos = 96;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...textDark);
  doc.text('Executive Summary', margin, yPos);

  yPos += 12;

  // Draw 4 Metric Cards
  const cardGap = 10;
  const cardWidth = (pageWidth - (margin * 2) - (cardGap * 3)) / 4;
  const cardHeight = 46;

  const stats = [
    { label: 'TOTAL SCANS', val: `${total}`, color: brandBlue, bg: [239, 246, 255] },
    { label: 'COMPLIANT', val: `${compliant} (${compRate}%)`, color: safeGreen, bg: [240, 253, 244] },
    { label: 'NON-COMPLIANT', val: `${nonCompliant}`, color: alertRed, bg: [254, 242, 242] },
    { label: 'NEEDS REVIEW', val: `${review}`, color: alertAmber, bg: [255, 251, 235] },
  ];

  stats.forEach((st, i) => {
    const xPos = margin + i * (cardWidth + cardGap);
    // Background
    doc.setFillColor(...st.bg);
    doc.roundedRect(xPos, yPos, cardWidth, cardHeight, 4, 4, 'F');
    // Border
    doc.setDrawColor(...st.color);
    doc.setLineWidth(1);
    doc.roundedRect(xPos, yPos, cardWidth, cardHeight, 4, 4, 'D');

    // Label
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...textMuted);
    doc.text(st.label, xPos + 8, yPos + 14);

    // Value
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...st.color);
    doc.text(st.val, xPos + 8, yPos + 34);
  });

  yPos += cardHeight + 16;

  // Filter info line
  const filterTexts = [];
  if (verdictFilter) filterTexts.push(`Verdict: ${verdictFilter.replace('_', ' ')}`);
  if (searchQuery) filterTexts.push(`Search: "${searchQuery}"`);
  if (filterTexts.length > 0) {
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(...textMuted);
    doc.text(`Active Filter: ${filterTexts.join(' | ')} (Showing ${scans.length} records)`, margin, yPos);
    yPos += 14;
  }

  // 3. Scans Table
  const tableData = scans.map((s, idx) => {
    const v = s.verdict || 'UNKNOWN';
    const verdictLabel = v === 'COMPLIANT' ? 'COMPLIANT' : v === 'NON_COMPLIANT' ? 'NON-COMPLIANT' : 'NEEDS REVIEW';
    const conf = s.overall_confidence != null ? `${Math.round(s.overall_confidence * 100)}%` : '—';
    const scanDate = s.created_at
      ? new Date(s.created_at).toLocaleString('en-IN', {
          day: '2-digit',
          month: 'short',
          hour: '2-digit',
          minute: '2-digit',
        })
      : '—';
    const scanId = (s.id || '').substring(0, 8).toUpperCase();
    const fileName = s.image_filename || s.generic_name || 'Label Scan';

    // Summary of failed rules or notes
    const failedRules = (s.rule_results || [])
      .filter(r => !r.passed && r.severity !== 'info')
      .map(r => r.rule_name || r.name)
      .filter(Boolean);

    const notes = failedRules.length > 0 ? `Failed: ${failedRules.join(', ')}` : s.needs_manual_review ? 'Low confidence / Manual check' : 'All standard checks passed';

    return [
      idx + 1,
      scanId,
      fileName,
      verdictLabel,
      conf,
      (s.detected_language || 'en').toUpperCase(),
      scanDate,
      notes,
    ];
  });

  autoTable(doc, {
    startY: yPos,
    head: [['#', 'Scan ID', 'Product / File', 'Verdict', 'Conf.', 'Lang', 'Timestamp', 'Compliance Findings']],
    body: tableData,
    margin: { left: margin, right: margin, bottom: 40 },
    theme: 'grid',
    styles: {
      fontSize: 8,
      cellPadding: 5,
      textColor: textDark,
      lineColor: [226, 232, 240],
      lineWidth: 0.5,
      overflow: 'linebreak',
    },
    headStyles: {
      fillColor: brandBlue,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
      halign: 'left',
    },
    columnStyles: {
      0: { cellWidth: 20, halign: 'center' },
      1: { cellWidth: 52, font: 'courier' },
      2: { cellWidth: 100 },
      3: { cellWidth: 78, fontStyle: 'bold' },
      4: { cellWidth: 36, halign: 'center' },
      5: { cellWidth: 32, halign: 'center' },
      6: { cellWidth: 70 },
      7: { cellWidth: 'auto' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 3) {
        const text = data.cell.raw;
        if (text === 'COMPLIANT') {
          data.cell.styles.textColor = safeGreen;
        } else if (text === 'NON-COMPLIANT') {
          data.cell.styles.textColor = alertRed;
        } else {
          data.cell.styles.textColor = alertAmber;
        }
      }
    },
    didDrawPage: () => {
      const pageNumber = doc.internal.getCurrentPageInfo().pageNumber;
      const totalPages = doc.internal.getNumberOfPages();

      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...textMuted);

      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.5);
      doc.line(margin, pageHeight - 24, pageWidth - margin, pageHeight - 24);

      doc.text(
        'LabelSure Compliance Platform — Official Legal Metrology Regulatory Inspection Record',
        margin,
        pageHeight - 12
      );
      doc.text(
        `Page ${pageNumber} of ${totalPages}`,
        pageWidth - margin,
        pageHeight - 12,
        { align: 'right' }
      );
    },
  });

  const filename = `labelsure_compliance_report_${now.toISOString().slice(0, 10)}.pdf`;
  triggerDownload(doc, filename);
}

/**
 * Generates an in-depth Single Scan Compliance Audit PDF.
 * 
 * @param {Object} scan - Complete scan details including rule_results & fields
 * @param {Object} [user] - Logged in officer
 */
export function exportSingleScanPdf(scan, user = null) {
  if (!scan) return;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 36;

  const brandBlue = [21, 101, 192];
  const brandTeal = [0, 137, 123];
  const safeGreen = [46, 125, 50];
  const alertRed = [198, 40, 40];
  const alertAmber = [217, 119, 6];
  const textDark = [30, 41, 59];
  const textMuted = [100, 116, 139];

  // Header Banner
  doc.setFillColor(...brandBlue);
  doc.rect(0, 0, pageWidth, 72, 'F');
  doc.setFillColor(...brandTeal);
  doc.rect(0, 72, pageWidth, 4, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('LabelSure Inspection Certificate', margin, 32);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(224, 242, 254);
  doc.text('Packaged Commodity Compliance Audit Record', margin, 48);

  const now = new Date();
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(`Scan ID: ${(scan.id || '').toUpperCase()}`, pageWidth - margin, 32, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${now.toLocaleDateString('en-IN')}`, pageWidth - margin, 46, { align: 'right' });
  doc.text(`Auditor: ${user?.name || user?.email || 'Officer'}`, pageWidth - margin, 60, { align: 'right' });

  let yPos = 96;

  // Verdict Section
  const v = scan.verdict || 'UNKNOWN';
  const vColor = v === 'COMPLIANT' ? safeGreen : v === 'NON_COMPLIANT' ? alertRed : alertAmber;
  const vBg = v === 'COMPLIANT' ? [240, 253, 244] : v === 'NON_COMPLIANT' ? [254, 242, 242] : [255, 251, 235];

  doc.setFillColor(...vBg);
  doc.roundedRect(margin, yPos, pageWidth - margin * 2, 44, 6, 6, 'F');
  doc.setDrawColor(...vColor);
  doc.setLineWidth(1.5);
  doc.roundedRect(margin, yPos, pageWidth - margin * 2, 44, 6, 6, 'D');

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...vColor);
  doc.text(`VERDICT: ${v.replace('_', ' ')}`, margin + 16, yPos + 26);

  const passCount = (scan.rule_results || []).filter(r => r.passed).length;
  const totalRules = (scan.rule_results || []).length;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...textDark);
  doc.text(
    `${passCount} of ${totalRules} rules passed | Confidence: ${Math.round((scan.overall_confidence || 0) * 100)}%`,
    pageWidth - margin - 16,
    yPos + 26,
    { align: 'right' }
  );

  yPos += 58;

  // Extracted Label Declarations Section
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...textDark);
  doc.text('Extracted Mandatory Declarations', margin, yPos);

  yPos += 10;

  const fieldLabels = {
    manufacturer_name: 'Manufacturer / Packer',
    manufacturer_address: 'Manufacturer Address',
    generic_name: 'Commodity / Product Name',
    net_quantity_value: 'Net Quantity',
    net_quantity_unit: 'Unit of Measure',
    mrp: 'Maximum Retail Price (₹)',
    manufacture_month: 'Mfg Month',
    manufacture_year: 'Mfg Year',
    batch_number: 'Batch / Lot Number',
    expiry_date: 'Best Before / Expiry',
    fssai_license: 'FSSAI License No.',
    consumer_care: 'Consumer Care Helpline',
    country_of_origin: 'Country of Origin',
    measured_font_height_mm: 'Measured Font Height (mm)',
  };

  const fields = (scan.fields || scan.extracted_fields || []).filter(f => f.field_value);
  const fieldRows = fields.map(f => [
    fieldLabels[f.field_name] || f.field_name,
    f.field_value || '—',
  ]);

  if (fieldRows.length > 0) {
    autoTable(doc, {
      startY: yPos,
      head: [['Mandatory Field', 'Extracted Value']],
      body: fieldRows,
      margin: { left: margin, right: margin },
      theme: 'striped',
      styles: { fontSize: 8.5, cellPadding: 4 },
      headStyles: { fillColor: brandBlue, textColor: [255, 255, 255], fontStyle: 'bold' },
      columnStyles: { 0: { cellWidth: 160, fontStyle: 'bold' } },
    });
    yPos = (doc.lastAutoTable ? doc.lastAutoTable.finalY : yPos + 80) + 16;
  }

  // Legal Metrology Rules Check Results
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...textDark);
  doc.text('Legal Metrology Rule Verification Results', margin, yPos);

  yPos += 10;

  const ruleRows = (scan.rule_results || []).map(r => {
    const isInfo = r.severity === 'info';
    const status = isInfo ? 'INFO' : r.passed ? 'PASSED' : 'FAILED';
    return [
      r.rule_name || r.name || 'Rule',
      status,
      r.legal_reference || r.act_rule || 'Legal Metrology Rules',
      r.explanation || 'Verification completed',
    ];
  });

  autoTable(doc, {
    startY: yPos,
    head: [['Rule Name', 'Status', 'Legal Reference', 'Finding / Assessment']],
    body: ruleRows,
    margin: { left: margin, right: margin, bottom: 40 },
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 4 },
    headStyles: { fillColor: brandBlue, textColor: [255, 255, 255], fontStyle: 'bold' },
    columnStyles: {
      0: { cellWidth: 120, fontStyle: 'bold' },
      1: { cellWidth: 55, halign: 'center', fontStyle: 'bold' },
      2: { cellWidth: 100 },
      3: { cellWidth: 'auto' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 1) {
        if (data.cell.raw === 'PASSED') data.cell.styles.textColor = safeGreen;
        else if (data.cell.raw === 'FAILED') data.cell.styles.textColor = alertRed;
        else data.cell.styles.textColor = alertAmber;
      }
    },
    didDrawPage: () => {
      const pageNumber = doc.internal.getCurrentPageInfo().pageNumber;
      const totalPages = doc.internal.getNumberOfPages();
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...textMuted);
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.5);
      doc.line(margin, pageHeight - 24, pageWidth - margin, pageHeight - 24);
      doc.text(
        `LabelSure Inspection Certificate — Scan ${scan.id?.substring(0, 8).toUpperCase()}`,
        margin,
        pageHeight - 12
      );
      doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - margin, pageHeight - 12, { align: 'right' });
    },
  });

  const filename = `labelsure_scan_${scan.id?.substring(0, 8) || 'report'}.pdf`;
  triggerDownload(doc, filename);
}
